#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Getopt-Euclid
Version  : 0.4.8
Release  : 35
URL      : https://cpan.metacpan.org/authors/id/B/BI/BIGPRESH/Getopt-Euclid-0.4.8.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BI/BIGPRESH/Getopt-Euclid-0.4.8.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libg/libgetopt-euclid-perl/libgetopt-euclid-perl_0.4.5-2.debian.tar.xz
Summary  : 'Executable Uniform Command-Line Interface Descriptions'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Getopt-Euclid-license = %{version}-%{release}
Requires: perl-Getopt-Euclid-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(IO::Pager::Page)
BuildRequires : perl(Pod::PlainText)
BuildRequires : perl(Pod::Select)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Getopt::Euclid - Executable Uniform Command-Line Interface Descriptions
VERSION

%package dev
Summary: dev components for the perl-Getopt-Euclid package.
Group: Development
Provides: perl-Getopt-Euclid-devel = %{version}-%{release}
Requires: perl-Getopt-Euclid = %{version}-%{release}

%description dev
dev components for the perl-Getopt-Euclid package.


%package license
Summary: license components for the perl-Getopt-Euclid package.
Group: Default

%description license
license components for the perl-Getopt-Euclid package.


%package perl
Summary: perl components for the perl-Getopt-Euclid package.
Group: Default
Requires: perl-Getopt-Euclid = %{version}-%{release}
Requires: perl(IO::Pager::Page)

%description perl
perl components for the perl-Getopt-Euclid package.


%prep
%setup -q -n Getopt-Euclid-0.4.8
cd %{_builddir}
tar xf %{_sourcedir}/libgetopt-euclid-perl_0.4.5-2.debian.tar.xz
cd %{_builddir}/Getopt-Euclid-0.4.8
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Getopt-Euclid-0.4.8/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Getopt-Euclid
cp %{_builddir}/Getopt-Euclid-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Getopt-Euclid/9f46d255c7fbeb63cacfe849b5aa834e5c0cdc73 || :
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Getopt-Euclid/fb5c9d1c927eb97797bffdffd5c04e08e9bcd546 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Getopt::Euclid.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Getopt-Euclid/9f46d255c7fbeb63cacfe849b5aa834e5c0cdc73
/usr/share/package-licenses/perl-Getopt-Euclid/fb5c9d1c927eb97797bffdffd5c04e08e9bcd546

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
